package com.codecat.directtochat

/**This file holds an instance of an [ArrayList] object which references all the countries pre defined in this project.
 * */
val countries = arrayListOf(
    Country("Afghanistan","AF","93",R.mipmap.af),
    Country("Aland Islands","AX","358",R.mipmap.ax),
    Country("Albania","AL","355",R.mipmap.al),
    Country("Algeria","DZ","213",R.mipmap.dz),
    Country("American Samoa","AS","1684", R.mipmap.`as`),
    Country("Andorra","AD","376",R.mipmap.ad),
    Country("Angola","AO","244",R.mipmap.ao),
    Country("Anguilla","AI","1264",R.mipmap.ai),
    Country("Antarctica","AQ","672",R.mipmap.aq),
    Country("Antigua and Barbuda","AG","1268",R.mipmap.ag),
    Country("Argentina","AR","54",R.mipmap.ar),
    Country("Armenia","AM","374",R.mipmap.am),
    Country("Aruba","AW","297",R.mipmap.aw),
    Country("Australia","AU","61",R.mipmap.au),
    Country("Austria","AT","43",R.mipmap.at),
    Country("Azerbaijan","AZ","994",R.mipmap.az),
    Country("Bahamas","BS","1242",R.mipmap.bs),
    Country("Bahrain","BH","973",R.mipmap.bh),
    Country("Bangladesh","BD","880",R.mipmap.bd),
    Country("Barbados","BB","1246",R.mipmap.bb),
    Country("Belarus","BY","375",R.mipmap.by),
    Country("Belgium","BE","32",R.mipmap.be),
    Country("Belize","BZ","501",R.mipmap.bz),
    Country("Benin","BJ","229",R.mipmap.bj),
    Country("Bermuda","BM","1441",R.mipmap.bm),
    Country("Bhutan","BT","975",R.mipmap.bt),
    Country("Bolivia","BO","591",R.mipmap.bo),
    Country("Bonaire","BQ","599",R.mipmap.bq),
    Country("Bosnia and Herzegovina","BA","387",R.mipmap.ba),
    Country("Botswana","BW","267",R.mipmap.bw),
    Country("Bouvet Island","BV","55",R.mipmap.bv),
    Country("Brazil","BR","55",R.mipmap.br),
    Country("British Indian Ocean Territory","IO","246",R.mipmap.io),
    Country("British Virgin Islands","VG","1284",R.mipmap.vg),
    Country("Brunei","BN","673",R.mipmap.bn),
    Country("Bulgaria","BG","359",R.mipmap.bg),
    Country("Burkina Faso","BF","226",R.mipmap.bf),
    Country("Burundi","BI","257",R.mipmap.bi),
    Country("Cambodia","KH","855",R.mipmap.kh),
    Country("Cameroon","CM","237",R.mipmap.cm),
    Country("Canada","CA","1",R.mipmap.ca),
    Country("Cape Verde","CV","238",R.mipmap.cv),
    Country("Cayman Islands","KY","1345",R.mipmap.ky),
    Country("Central African Republic","CF","236",R.mipmap.cf),
    Country("Chad","TD","235",R.mipmap.td),
    Country("Chile","CL","56",R.mipmap.cl),
    Country("China","CN","86",R.mipmap.cn),
    Country("Christmas Island","CX","61",R.mipmap.cx),
    Country("Cocos Islands","CC","61",R.mipmap.cc),
    Country("Colombia","CO","57",R.mipmap.co),
    Country("Comoros","KM","269",R.mipmap.km),
    Country("Congo","CG","242",R.mipmap.cg),
    Country("Cook Islands","CK","682",R.mipmap.ck),
    Country("Costa Rica","CR","506",R.mipmap.cr),
    Country("Croatia","HR","385",R.mipmap.hr),
    Country("Cuba","CU","53",R.mipmap.cu),
    Country("Curacao","CW","599",R.mipmap.cw),
    Country("Cyprus","CY","357",R.mipmap.cy),
    Country("Czech Republic","CZ","420",R.mipmap.cz),
    Country("Democratic Republic of Congo","CD","243",R.mipmap.cd),
    Country("Denmark","DK","45",R.mipmap.dk),
    Country("Djibouti","DJ","253",R.mipmap.dj),
    Country("Dominica","DM","1767",R.mipmap.dm),
    Country("Dominican Republic","DO","1809",R.mipmap.f_do),
    Country("Ecuador","EC","593",R.mipmap.ec),
    Country("Egypt","EG","20",R.mipmap.eg),
    Country("El Salvador","SV","503",R.mipmap.sv),
    Country("England","ENG","44",R.mipmap.eng),
    Country("Equatorial Guinea","GQ","240",R.mipmap.gq),
    Country("Eritrea","ER","291",R.mipmap.er),
    Country("Estonia","EE","372",R.mipmap.ee),
    Country("Ethiopia","ET","251",R.mipmap.et),
    Country("Falkland Islands","FK","500",R.mipmap.fk),
    Country("Faroe Islands","FO","298",R.mipmap.fo),
    Country("Fiji","FJ","679",R.mipmap.fj),
    Country("Finland","FI","358",R.mipmap.fi),
    Country("France","FR","33",R.mipmap.fr),
    Country("French Guiana","GF","594",R.mipmap.gf),
    Country("French Polynesia","PF","689",R.mipmap.pf),
    Country("French Southern Territories","TF","262",R.mipmap.tf),
    Country("Gabon","GA","241",R.mipmap.ga),
    Country("Gambia","GM","220",R.mipmap.gm),
    Country("Georgia","GE","995",R.mipmap.ge),
    Country("Germany","DE","49",R.mipmap.de),
    Country("Ghana","GH","233",R.mipmap.gh),
    Country("Gibraltar","GI","350",R.mipmap.gi),
    Country("Greece","GR","30",R.mipmap.gr),
    Country("Greenland","GL","299",R.mipmap.gl),
    Country("Grenada","GD","1473",R.mipmap.gd),
    Country("Guadeloupe","GP","590",R.mipmap.gp),
    Country("Guam","GU","1671",R.mipmap.gu),
    Country("Guatemala","GT","502",R.mipmap.gt),
    Country("Guernsey","GG","44",R.mipmap.gg),
    Country("Guinea","GN","224",R.mipmap.gn),
    Country("Guinea-Bissau","GW","245",R.mipmap.gw),
    Country("Guyana","GY","592",R.mipmap.gy),
    Country("Haiti","HT","509",R.mipmap.ht),
    Country("Heard Island and McDonald Islands","HM","672",R.mipmap.hm),
    Country("Honduras","HN","504",R.mipmap.hn),
    Country("Hong Kong","HK","852",R.mipmap.hk),
    Country("Hungary","HU","36",R.mipmap.hu),
    Country("Iceland","IS","354",R.mipmap.`is`),
    Country("India","IN","91",R.mipmap.`in`),
    Country("Indonesia","ID","62",R.mipmap.id),
    Country("Iran","IR","98",R.mipmap.ir),
    Country("Iraq","IQ","964",R.mipmap.iq),
    Country("Ireland","IE","353",R.mipmap.ie),
    Country("Isle of Man","IM","44",R.mipmap.im),
    Country("Israel","IL","972",R.mipmap.il),
    Country("Italy","IT","39",R.mipmap.it),
    Country("Ivory Coast","CI","225",R.mipmap.ci),
    Country("Jamaica","JM","1876",R.mipmap.jm),
    Country("Japan","JP","81",R.mipmap.jp),
    Country("Jersey","JE","44",R.mipmap.je),
    Country("Jordan","JO","962",R.mipmap.jo),
    Country("Kazakhstan","KZ","7",R.mipmap.kz),
    Country("Kenya","KE","254",R.mipmap.ke),
    Country("Kiribati","KI","686",R.mipmap.ki),
    Country("Kosovo","XK","383",R.mipmap.xk),
    Country("Kuwait","KW","965",R.mipmap.kw),
    Country("Kyrgyzstan","KG","996",R.mipmap.kg),
    Country("Laos","LA","856",R.mipmap.la),
    Country("Latvia","LV","371",R.mipmap.lv),
    Country("Lebanon","LB","961",R.mipmap.lb),
    Country("Lesotho","LS","266",R.mipmap.ls),
    Country("Liberia","LR","231",R.mipmap.lr),
    Country("Libya","LY","218",R.mipmap.ly),
    Country("Liechtenstein","LI","423",R.mipmap.li),
    Country("Lithuania","LT","370",R.mipmap.lt),
    Country("Luxembourg","LU","352",R.mipmap.lu),
    Country("Macau","MO","853",R.mipmap.mo),
    Country("Macedonia","MK","389",R.mipmap.mk),
    Country("Madagascar","MG","261",R.mipmap.mg),
    Country("Malawi","MW","265",R.mipmap.mw),
    Country("Malaysia","MY","60",R.mipmap.my),
    Country("Maldives","MV","960",R.mipmap.mv),
    Country("Mali","ML","223",R.mipmap.ml),
    Country("Malta","MT","356",R.mipmap.mt),
    Country("Marshall Islands","MH","692",R.mipmap.mh),
    Country("Martinique","MQ","596",R.mipmap.mq),
    Country("Mauritania","MR","222",R.mipmap.mr),
    Country("Mauritius","MU","230",R.mipmap.mu),
    Country("Mayotte","YT","262",R.mipmap.yt),
    Country("Mexico","MX","52",R.mipmap.mx),
    Country("Micronesia","FM","691",R.mipmap.fm),
    Country("Moldova","MD","373",R.mipmap.md),
    Country("Monaco","MC","377",R.mipmap.mc),
    Country("Mongolia","MN","976",R.mipmap.mn),
    Country("Montenegro","ME","382",R.mipmap.me),
    Country("Montserrat","MS","1664",R.mipmap.ms),
    Country("Morocco","MA","212",R.mipmap.ma),
    Country("Mozambique","MZ","258",R.mipmap.mz),
    Country("Myanmar","MM","95",R.mipmap.mm),
    Country("Namibia","NA","264",R.mipmap.na),
    Country("Nauru","NR","674",R.mipmap.nr),
    Country("Nepal","NP","977",R.mipmap.np),
    Country("Netherlands","NL","31",R.mipmap.nl),
    Country("Netherlands Antilles","AN","599",0),
    Country("New Caledonia","NC","687",R.mipmap.nc),
    Country("New Zealand","NZ","64",R.mipmap.nz),
    Country("Nicaragua","NI","505",R.mipmap.ni),
    Country("Niger","NE","227",R.mipmap.ne),
    Country("Nigeria","NG","234",R.mipmap.ng),
    Country("Niue","NU","683",R.mipmap.nu),
    Country("Norfolk Island","NF","672",R.mipmap.nf),
    Country("North Korea","KP","850",R.mipmap.kp),
    Country("Northern Ireland","NIR","44",0),
    Country("Northern Mariana Islands","MP","1670",R.mipmap.mp),
    Country("Norway","NO","47",R.mipmap.no),
    Country("Oman","OM","968",R.mipmap.om),
    Country("Pakistan","PK","92",R.mipmap.pk),
    Country("Palau","PW","680",R.mipmap.pw),
    Country("Palestine","PS","970",R.mipmap.ps),
    Country("Panama","PA","507",R.mipmap.pa),
    Country("Papua New Guinea","PG","675",R.mipmap.pg),
    Country("Paraguay","PY","595",R.mipmap.py),
    Country("Peru","PE","51",R.mipmap.pe),
    Country("Philippines","PH","63",R.mipmap.ph),
    Country("Pitcairn Islands","PN","64",R.mipmap.pn),
    Country("Poland","PL","48",R.mipmap.pl),
    Country("Portugal","PT","351",R.mipmap.pt),
    Country("Puerto Rico","PR","1787",R.mipmap.pr),
    Country("Qatar","QA","974",R.mipmap.qa),
    Country("Reunion","RE","262",R.mipmap.re),
    Country("Romania","RO","40",R.mipmap.ro),
    Country("Russia","RU","7",R.mipmap.ru),
    Country("Rwanda","RW","250",R.mipmap.rw),
    Country("Saint Barthelemy","BL","590",R.mipmap.bl),
    Country("Saint Helena Ascension and Tristan da Cunha","SH","290",R.mipmap.sh),
    Country("Saint Kitts and Nevis","KN","1869",R.mipmap.kn),
    Country("Saint Lucia","LC","1758",R.mipmap.lc),
    Country("Saint Martin","MF","590",R.mipmap.mf),
    Country("Saint Pierre and Miquelon","PM","508",R.mipmap.pm),
    Country("Saint Vincent and the Grenadines","VC","1784",R.mipmap.vc),
    Country("Samoa","WS","685",R.mipmap.ws),
    Country("San Marino","SM","378",R.mipmap.sm),
    Country("Sao Tome and Principe","ST","239",R.mipmap.st),
    Country("Saudi Arabia","SA","966",R.mipmap.sa),
    Country("Scotland","SCT","44",R.mipmap.sct),
    Country("Senegal","SN","221",R.mipmap.sn),
    Country("Serbia","RS","381",R.mipmap.rs),
    Country("Seychelles","SC","248",R.mipmap.sc),
    Country("Sierra Leone","SL","232",R.mipmap.sl),
    Country("Singapore","SG","65",R.mipmap.sg),
    Country("Sint Maarten","SX","1721",R.mipmap.sx),
    Country("Slovakia","SK","421",R.mipmap.sk),
    Country("Slovenia","SI","386",R.mipmap.si),
    Country("Solomon Islands","SB","677",R.mipmap.sb),
    Country("Somalia","SO","252",R.mipmap.so),
    Country("South Africa","ZA","27",R.mipmap.za),
    Country("South Georgia and the South Sandwich Islands","GS","500",R.mipmap.gs),
    Country("South Korea","KR","82",R.mipmap.kr),
    Country("South Sudan","SS","211",R.mipmap.ss),
    Country("Spain","ES","34",R.mipmap.es),
    Country("Sri Lanka","LK","94",R.mipmap.lk),
    Country("Sudan","SD","249",R.mipmap.sd),
    Country("Suriname","SR","597",R.mipmap.sr),
    Country("Svalbard and Jan Mayen","SJ","47",R.mipmap.sj),
    Country("Swaziland","SZ","268",R.mipmap.sz),
    Country("Sweden","SE","46",R.mipmap.se),
    Country("Switzerland","CH","41",R.mipmap.ch),
    Country("Syria","SY","963",R.mipmap.sy),
    Country("Taiwan","TW","886",R.mipmap.tw),
    Country("Tajikistan","TJ","992",R.mipmap.tj),
    Country("Tanzania","TZ","255",R.mipmap.tz),
    Country("Thailand","TH","66",R.mipmap.th),
    Country("Timor-Leste","TL","670",R.mipmap.tl),
    Country("Togo","TG","228",R.mipmap.tg),
    Country("Tokelau","TK","690",R.mipmap.tk),
    Country("Tonga","TO","676",R.mipmap.to),
    Country("Trinidad and Tobago","TT","1868",R.mipmap.tt),
    Country("Tunisia","TN","216",R.mipmap.tn),
    Country("Turkey","TR","90",R.mipmap.tr),
    Country("Turkmenistan","TM","993",R.mipmap.tm),
    Country("Turks and Caicos Islands","TC","1649",R.mipmap.tc),
    Country("Tuvalu","TV","688",R.mipmap.tv),
    Country("UAE","AE","971",R.mipmap.ae),
    Country("Uganda","UG","256",R.mipmap.ug),
    Country("UK","GB","44",R.mipmap.gb),
    Country("Ukraine","UA","380",R.mipmap.ua),
    Country("Uruguay","UY","598",R.mipmap.uy),
    Country("US Minor Outlying Islands","UM","1",R.mipmap.um),
    Country("US Virgin Islands","VI","1340",R.mipmap.vi),
    Country("USA","US","1",R.mipmap.us),
    Country("Uzbekistan","UZ","998",R.mipmap.uz),
    Country("Vanuatu","VU","678",R.mipmap.vu),
    Country("Vatican City","VA","379",R.mipmap.va),
    Country("Venezuela","VE","58",R.mipmap.ve),
    Country("Vietnam","VN","84",R.mipmap.vn),
    Country("Wales","WLS","44",R.mipmap.wls),
    Country("Wallis and Futuna","WF","681",R.mipmap.wf),
    Country("Western Sahara","EH","212",R.mipmap.eh),
    Country("Yemen","YE","967",R.mipmap.ye),
    Country("Zambia","ZM","260",R.mipmap.zm),
    Country("Zimbabwe","ZW","263",R.mipmap.zw)
)